# --------------------#--------------------#--------------------
#
#   WARNING  WARNING  WARNING  WARNING  WARNING
#
#   This is a serverless config used only to deploy a cognito 
#   user pool to be used by your local environment
#
# --------------------#--------------------#--------------------
service: ${file(./.env.${sls:stage}.json):SERVICE_NAME}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: local
  profile: ${file(./.env.${sls:stage}.json):PROFILE}
  architecture: arm64

resources:
  - ${file(./stack/cognito.yml)}
