service: ${file(./.env.${sls:stage}.json):SERVICE_NAME}
frameworkVersion: '3'
	
# New syntax
package:
  patterns:
    - api/**
    - api/*
    - node_modules/*
    - node_modules/**
    - '!node_modules/aws-sdk'
    - '!node_modules/dotenv'
    - '!node_modules/mocha'
    - '!node_modules/nodemon'
    - '!node_modules/serverless'
    - '!.serverless/*'
    - '!.serverless/**'
    - '!*.yml'
    - '!*.md'
    - '!.env'
    - '!vue-app/*'
    - '!vue-app/**'
    - '!vue-app'
    - '!my-dynamodb-data/*'
    - '!my-dynamodb-data/**'
    - '!local.sh'
    - '!*.json'
    - '.gitignore'
    - '!deploy.js'
    - '!node_modules/concurrently'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  profile: ${file(./.env.${sls:stage}.json):PROFILE}
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment: ${file(./.env.${sls:stage}.json)}

functions:
  api:
    handler: api/handler.handler
    events:
      - httpApi: '*'

resources: 
  - ${file(./stack/dynamoTables.yml)}
  - ${file(./stack/cognito.yml)}
  - ${file(./stack/s3Buckets.yml)}