Resources: 
  SpaSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.STATIC_BUCKET}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - "x-amz-server-side-encryption"
              - "x-amz-request-id"
              - "x-amz-id-2"
            Id: SpaSiteBucket
            MaxAge: 3000